#!/usr/bin/env bash
#
# Uses bash.


#
# Does this linter handle the file?
#


file="$1"

# check shebang
shebang=$(awk '/^#\!/ {print $2; exit}' "$file")
[ "$shebang" != "bash" ] && exit 2



#
# Lint the file.
#

# suppress output when syntax is ok
bash -n "$1" > /dev/null

