#!/usr/bin/env bash
#
# Uses bash.


#
# Does this linter handle the file?
#

if [ "$1" == "--handles" ]; then

  file="$2"

  # check shebang
  shebang=$(awk '/^#\!/ {print $2; exit}' "$file")
  if [ "$shebang" == "bash" ]; then
    exit 0
  fi

  # this is not the linter you are looking for
  exit 1
fi


#
# Lint the file.
#

# suppress output when syntax is ok
bash -n "$1" > /dev/null

