#!/usr/bin/env bash
#
# Uses bash.


#
# Does this linter handle the file?
#


file="$1"

# check shebang
shebang=$(head -n1 "$file" | grep '^#!' | cut -d' ' -f2)
[ "$shebang" != "bash" ] && exit 2



#
# Lint the file.
#

# suppress output when syntax is ok
bash -n "$1" > /dev/null

