#!/usr/bin/env bash
#
# Uses coffeescript's compiler.
# Install with: npm install -g coffee-script


#
# Does this linter handle the file?
#


file="$1"
extension="${file##*.}"

# check extension
[ "$extension" != "coffee" ] && exit 2



#
# Lint the file.
#

# suppress output when syntax is ok
coffee --compile --print "$1" > /dev/null

