#!/usr/bin/env bash
#
# Uses ruby's ERB compiler.


#
# Does this linter handle the file?
#

if [ "$1" == "--handles" ]; then

  file="$2"
  extension="${file##*.}"

  # check extension
  if [ "$extension" == "erb" ]; then
    exit 0
  fi

  # this is not the linter you are looking for
  exit 1
fi


#
# Lint the file.
#

# suppress output when syntax is ok
erb -xT- "$1" | ruby -c > /dev/null

