#!/usr/bin/env bash
#
# Uses ruby's ERB compiler.


#
# Does this linter handle the file?
#


file="$1"
extension="${file##*.}"

# check extension
[ "$extension" != "erb" ] && exit 2


#
# Lint the file.
#

# suppress output when syntax is ok
erb -xT- "$1" | ruby -c > /dev/null

