#!/usr/bin/env bash
#
# Uses haml's compiler.


#
# Does this linter handle the file?
#

file="$2"
extension="${file##*.}"

# check extension
[ "$extension" != "haml" ] && exit 2



#
# Lint the file.
#

# suppress output when syntax is ok
haml --check "$1" > /dev/null

