#!/usr/bin/env bash
#
# Uses haml's compiler.


#
# Does this linter handle the file?
#

if [ "$1" == "--handles" ]; then

  file="$2"
  extension="${file##*.}"

  # check extension
  exit $([ "$extension" == "haml" ])

fi


#
# Lint the file.
#

# suppress output when syntax is ok
haml --check "$1" > /dev/null

