#!/usr/bin/env bash
#
# Uses eslint (https://eslint.org) v8.8.0
#
# Installed with `yarn global add eslint`

is_javascript() {
  [ "$2" == "js" ]
}

lint_javascript() {
  eslint --env browser --parser-options ecmaVersion:2022,sourceType:module --quiet "$1"
}
