#!/usr/bin/env bash
#
# Uses acorn (https://github.com/ternjs/acorn)
# Install with: npm install -g acorn


#
# Does this linter handle the file?
#

file="$1"
extension="${file##*.}"

# check extension
[ "$extension" != "js" ] && exit 2



#
# Lint the file.
#

acorn --silent "$1"

