#!/usr/bin/env bash

is_ruby() {
  [ "$2" == "rb" ]      || \
  [ "$2" == "rake" ]    || \
  [ "$2" == "builder" ] || \

  [ "$1" == "Capfile"   ] || \
  [ "$1" == "Gemfile"   ] || \
  [ "$1" == "Rakefile"  ] || \
  [ "$1" == "config.ru" ] || \

  [ "$3" == "ruby" ]
}

lint_ruby() {
  ruby -c "$1"
}

