#!/usr/bin/env bash
#
# Uses ruby's compiler.


#
# Does this linter handle the file?
#


file="$1"
name=$(basename "$file")
extension="${file##*.}"

extension() {
  [ "$extension" == "rb"      ] || \
  [ "$extension" == "rake"    ] || \
  [ "$extension" == "builder" ]
}

name() {
  [ "$name" == "Capfile"   ] || \
  [ "$name" == "Gemfile"   ] || \
  [ "$name" == "Rakefile"  ] || \
  [ "$name" == "config.ru" ]
}

shebang() {
  shebang=$(head -n1 "$file" | grep '^#!' | cut -d' ' -f2)
  [ "$shebang" == "ruby" ]
}

! (extension || name || shebang) && exit 2


#
# Lint the file.
#

# suppress output when syntax is ok
ruby -c "$1" > /dev/null

