#!/usr/bin/env bash
#
# Uses sass's compiler.


#
# Does this linter handle the file?
#


file="$1"
extension="${file##*.}"

# check extension
[ "$extension" != "sass" ] && [ "$extension" != "scss" ] && exit 2



#
# Lint the file.
#

# treat warnings as syntax errors

# errors are indicated by non-zero exit code from sass command.
result=$(node_modules/.bin/node-sass -q "$1" > /dev/null)
if [ $? -eq 1 ]; then
  # output warning on stderr
  >&2 echo "$result"
  exit 1
fi

exit 0

