#!/usr/bin/env bash
#
# Uses ruby's stdlib.


#
# Does this linter handle the file?
#

if [ "$1" == "--handles" ]; then

  file="$2"
  extension="${file##*.}"

  # # check for linter dependency
  # if ! type yamllint > /dev/null 2>&1; then
  #   exit 1
  # fi

  # check extension
  if [ "$extension" == "yml" ] || [ "$extension" == "yaml" ]; then
    exit 0
  fi

  # this is not the linter you are looking for
  exit 1
fi


#
# Lint the file.
#

ruby -e "require 'yaml'; YAML.load_file('$1')"

