#!/usr/bin/env bash
#
# Uses ruby's stdlib.


#
# Does this linter handle the file?
#


file="$2"
extension="${file##*.}"

# check extension
[ "$extension" != "yml" ] && [ "$extension" != "yaml" ] && exit 2


#
# Lint the file.
#

ruby -e "require 'yaml'; YAML.load_file('$1')"

